RecipeWebsite/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text.Json;
using System.Threading.Tasks;
using Ganss.Xss;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using RecipeWebsite.Data;
using RecipeWebsite.Models;

namespace RecipeWebsite.Controllers
{
    public class RecipeController : Controller
    {
        private readonly RecipeWebsiteContext _context;
        private readonly IWebHostEnvironment _environment;
        private readonly UserManager<User> _userManager;

        public RecipeController(RecipeWebsiteContext context, UserManager<User> userManager, IWebHostEnvironment environment)
        {
            _context = context;
            _userManager = userManager;
            _environment = environment;
        }

        /// <summary>
        /// Gets a list of Recipe objects from the database
        /// </summary>
        /// <returns></returns>
        // GET: Recipe
        public async Task<IActionResult> Index()
        {
              return _context.Recipe != null ? 
                          View(await _context.Recipe.ToListAsync()) :
                          Problem("Entity set 'RecipeWebsiteContext.Recipe'  is null.");
        }

        /// <summary>
        /// Gets the details from the recipe that was clicked to display on view
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Recipe/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipe
                .Include(r => r.Ingredients)
                .Include(r => r.Author)
                .Include(r => r.Comments)
                .FirstOrDefaultAsync(m => m.RecipeId == id);
            if (recipe == null)
            {
                return NotFound();
            }

            // sanitize directions to avoid XSS vulnerability
            recipe.Directions = Sanitize(recipe.Directions);

            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser != null)
            {
                currentUser = _context.Users.Include(u => u.MyFavorites).FirstOrDefault(u => u.Id == currentUser.Id);
            }

            UserRatings currentUsersRating = _context.UserRatings.Where(r => r.RecipeId == recipe.RecipeId && r.UserRated == currentUser.Id).FirstOrDefault();
            int usersRatedNumber = -1;

            if(currentUsersRating != null) {
                usersRatedNumber = currentUsersRating.Rating;
            }

            var viewModel = new RecipeDetailsViewModel {
                Recipe = recipe,
                CurrentUser = currentUser,
                Rating = recipe.Rating,
                CurrentUsersRating = usersRatedNumber
            };

            return View(viewModel);
        }

        /// <summary>
        /// Gets the recipe fields ready for create view
        /// </summary>
        /// <returns></returns>
        // GET: Recipe/Create
        public IActionResult Create()
        {
            var viewModel = new RecipeViewModel();
            viewModel.Ingredients = new List<Ingredient>();
            return View(viewModel);
        }

        /// <summary>
        /// Creates a new recipe and inserts it into the database
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Create(RecipeViewModel viewModel)
        {
            //configure file upload url with user's file
            string fileName = "";
            if (viewModel.ImageUrl != null) {
                fileName = Guid.NewGuid().ToString();
                fileName += Path.GetExtension(viewModel.ImageUrl?.FileName);
                string uploadPath = Path.Combine(_environment.WebRootPath, "img", fileName);
                using Stream fileStream = new FileStream(uploadPath, FileMode.Create);
                await viewModel.ImageUrl.CopyToAsync(fileStream);
            }

            if (ModelState.IsValid)
            {
                var recipe = new Recipe();
                recipe.Title = viewModel.Title;
                recipe.ImageUrl = fileName; //!string.IsNullOrEmpty(viewModel.ImageUrl) ? viewModel.ImageUrl : "https://i.imgur.com/zIAshBo.png";
                recipe.Description = viewModel.Description;
                recipe.Category = viewModel.Category;
                recipe.SubCategory = viewModel.SubCategory;
                recipe.Directions = viewModel.Directions;
                recipe.DateCreated = DateTimeOffset.Now;

                // Assign Ingredients list from viewModel to Recipe
                recipe.Ingredients = viewModel.Ingredients.Select(i => { i.Recipe = recipe; return i; }).ToList();

                // Set the author to the currently logged in user
                recipe.Author = await _userManager.GetUserAsync(User);

                _context.Recipe.Add(recipe);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(viewModel);
        }

        /// <summary>
        /// Gets recipe fields from recipe ready for editing
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Recipe/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Use Include() to load the related Ingredients
            var recipe = await _context.Recipe.Include(r => r.Ingredients).FirstOrDefaultAsync(r => r.RecipeId == id.Value);

            if (recipe == null)
            {
                return NotFound();
            }
            
            //check if current user is not the recipe author
            User currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null || recipe.Author == null || recipe.Author.Id != currentUser.Id) {
                //MessageBox.Show("Access Denied");
                return RedirectToAction("Details", new { id = recipe.RecipeId });
            }

            var viewModel = new RecipeViewModel();
            viewModel.RecipeId = recipe.RecipeId;
            viewModel.Title = recipe.Title;
            viewModel.ExistingImage = "./img/" + recipe.ImageUrl;
            viewModel.Directions = recipe.Directions;
            viewModel.Description = recipe.Description;
            viewModel.Ingredients = recipe.Ingredients?.ToList() ?? new List<Ingredient>(); // Null-check and initialization if null

            return View(viewModel);
        }

        /// <summary>
        /// Modifies recipe information for specified recipe in database
        /// </summary>
        /// <param name="id"></param>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        // POST: Recipe/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, RecipeViewModel viewModel)
        {
            //configure file upload url with user's file
            string fileName = Guid.NewGuid().ToString();
            fileName += Path.GetExtension(viewModel.ImageUrl?.FileName);
            string uploadPath = Path.Combine(_environment.WebRootPath, "img", fileName);
            using Stream fileStream = new FileStream(uploadPath, FileMode.Create);
            await viewModel.ImageUrl.CopyToAsync(fileStream);

            if (id != viewModel.RecipeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid) // ModelState wants a Recipe object to be passed through a "Recipe field"
                                    // which is not possible. I've excluded it from the ModelState validation
            {
                try
                {
                    // Load the original recipe, including the ingredients
                    var originalRecipe = await _context.Recipe.Include(r => r.Ingredients).FirstOrDefaultAsync(r => r.RecipeId == id);

                    if (originalRecipe == null)
                    {
                        return NotFound();
                    }

                    // Update Recipe fields
                    originalRecipe.Title = viewModel.Title;
                    originalRecipe.ImageUrl = fileName;
                    originalRecipe.Category = viewModel.Category;
                    originalRecipe.SubCategory = "";
                    originalRecipe.Description = viewModel.Description;
                    originalRecipe.Directions = viewModel.Directions;

                    // Remove Ingredients
                    foreach (var ingredient in originalRecipe.Ingredients.ToList())
                    {
                        if (!viewModel.Ingredients.Any(i => i.IngredientId == ingredient.IngredientId))
                        {
                            _context.Entry(ingredient).State = EntityState.Deleted;
                        }
                    }

                    // Add and Update Ingredients
                    foreach (var viewModelIngredient in viewModel.Ingredients)
                    {
                        var originalIngredient = viewModelIngredient.IngredientId == 0 ? null :
                            originalRecipe.Ingredients.FirstOrDefault(i => i.IngredientId == viewModelIngredient.IngredientId);

RecipeWebsite/Views/Shared/Edit.cshtml
@model RecipeWebsite.Models.Comment

<h4>Comment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="View">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CommentId" />
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Votes" class="control-label"></label>
                <input asp-for="Votes" class="form-control" />
                <span asp-validation-for="Votes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RecipeWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecipeWebsite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RecipeWebsite.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark bottom_border set-font">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Recipe" asp-action="Index">GitGrub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Recipe" asp-action="Index">Home</a>
                        </li>
                        <li>
                        @if (User.Identity.IsAuthenticated) {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Recipe" asp-action="MyFavorites">My Favorites</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Recipe" asp-action="Create">Create A Recipe</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--For nutrition information modal-->
    <div class="modal fade" id="nutritionModal" role="dialog">
        <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>

    <!--For measurment converter modal-->
    <div class="modal fade" id="measurementModal" role="dialog">
        <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <h4>From</h4>
                    <br />

                    <select id="unit1" class="btn btn-secondary">
                        <option value="tsp">tsp</option>
                        <option value="tbsp">tbsp</option>
                        <option value="cup">cup</option>
                        <option value="oz">fl ounce</option>
                        <option value="pt">pint</option>
                        <option value="qt">quart</option>
                        <option value="gal">gallon</option>
                        <option value="ml">milliliter</option>
                        <option value="l">liter</option>
                    </select>

                    <label for="measure-number" class="text-dark">How Much</label>
                    <input id="amount" type="text" />
                    <br />
                    <br />


                    <h4>To</h4>
                    <br />

                    <select id="unit2" class="btn btn-secondary">
                        <option value="tsp">tsp</option>
                        <option value="tbsp">tbsp</option>
                        <option value="cup">cup</option>
                        <option value="oz">fl ounce</option>
                        <option value="pt">pint</option>
                        <option value="qt">quart</option>
                        <option value="gal">gallon</option>
                        <option value="ml">milliliter</option>
                        <option value="l">liter</option>
                    </select>
                    <br />
                    <br />

                    <button class="btn btn-outline-info" value="convert" onclick="convert()">Convert</button>

                    <label for="measurement-calculation-text">Result</label>
                    <input type="text" id="measurement-calculation-text" disabled/>
                    <br />
                    <br />

                    <h5 id="result-text">

                    </h5>
                </div>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RecipeWebsite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    @{
        var api = ApiHelper.apiKey();
    }

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script>
        //Nutrition Information API https://calorieninjas.com/
        function sendApi() {
            var food = $('#api-request').val();
            $.ajax({
                method: 'POST',
                url: '/Home/NutritionModal',
                data: JSON.stringify(food), 
                contentType: 'application/json',
                success: function (response) {
                    $('#nutritionModal .modal-body').html(response); 
                    $('#nutritionModal').modal('show'); 
                },
                error: function ajaxError(jqXHR) {
                    alert("error");
                    console.error('Error: ', jqXHR.responseText);
                }
            });
        }

        function openMeasureModal(){
            $('#measurementModal .modal-body').html();
            $('#measurementModal').modal('show');
        }

        function convert(){
            //get amount to convert
            var amount = $('#amount').val();

            if(!(isNaN(amount) || amount == "")){
                //get units of measurement
                var unit1 = $('#unit1').val();
                var unit2 = $('#unit2').val();

                const multipliers = new Map();

                multipliers.set("tsp", 48);
                multipliers.set("tbsp", 16);
                multipliers.set("cup", 1);
                multipliers.set("oz", 8);
                multipliers.set("pt", .5);
                multipliers.set("qt", .25);
                multipliers.set("gal", .06);
                multipliers.set("ml", 236.59);
                multipliers.set("l", .24);

                var conversion = (multipliers.get(unit2) * amount) / multipliers.get(unit1);
                conversion = parseFloat(conversion.toFixed(3));

                var result = document.getElementById("measurement-calculation-text");
                var displayValue = conversion.toString();
                result.value = displayValue;
                var resultMessage = document.getElementById("result-text");
                resultMessage.innerHTML = amount + " " + unit1 + "(s) = " + displayValue + " " + unit2;
            }
            else{
                alert("Please enter a valid amount");
            }
        } 
    </script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RecipeWebsite/Views/Shared/_NutritionModal.cshtml
@model List<NutritionInfoDTO>

<div class="demo" id="text-demo" style="">
    <div style="margin: 20px;">
        <h3>Nutrition Results</h3>
    </div>
    <div class="table-responsive">
        <table class="table table-striped" style="width: 100%;">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Serving Size</th>
                    <th scope="col">Calories</th>
                    <th scope="col">Total Fat</th>
                    <th scope="col">Saturated Fat</th>
                    <th scope="col">Cholesterol</th>
                    <th scope="col">Sodium</th>
                    <th scope="col">Carbohydrates</th>
                    <th scope="col">Fiber</th>
                    <th scope="col">Sugar</th>
                    <th scope="col">Protein</th>
                </tr>
            </thead>
            <tbody id="result">
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.name</td>
                        <td>@item.serving_size_g g</td>
                        <td>@item.calories</td>
                        <td>@item.fat_total_g g</td>
                        <td>@item.fat_saturated_g g</td>
                        <td>@item.cholesterol_mg mg</td>
                        <td>@item.sodium_mg mg</td>
                        <td>@item.carbohydrates_total_g g</td>
                        <td>@item.fiber_g g</td>
                        <td>@item.sugar_g g</td>
                        <td>@item.protein_g g</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>